### PR TITLE
Update output sections

### PR DESCRIPTION
**Pull request by asunar**

### CODE REVIEW

**Review by gabehollombe-aws — APPROVED** [review]
Great catch on this, thank you!

**Comment by asunar** [comment]
Thanks for putting it together. Do you have any plans for an API Gateway service integration with Step Functions workshop? No pressure :)

**Comment by gabehollombe-aws** [comment]
That's a great suggestion.  I'll put it on my TODOs and hopefully get to it sometime this quarter. If you're interested in taking a stab at it, I'm happy to review a PR and suggest improvements if you want to write a first draft yourself. No pressure, just being friendly and am totally open to collaborators from the community!

**Comment by asunar** [comment]
Sounds great, I will try to put something together.

**Pull request merged**
